"""added leader to player table

Revision ID: 1f7d6825647a
Revises: 19f4ff4e1319
Create Date: 2023-10-31 11:17:20.200254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f7d6825647a'
down_revision = '19f4ff4e1319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leader', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_column('leader')

    # ### end Alembic commands ###
