"""remove dummy

Revision ID: 8d7658cfdb80
Revises: c5263ba89a56
Create Date: 2023-11-03 10:21:25.593822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d7658cfdb80'
down_revision = 'c5263ba89a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('round', sa.Integer(), nullable=True))

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.drop_column('dummy')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dummy', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('round')

    # ### end Alembic commands ###
