"""added last votes for column of round table

Revision ID: 9c8843cc8fe5
Revises: b2de8636beda
Create Date: 2023-11-06 12:07:34.902386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c8843cc8fe5'
down_revision = 'b2de8636beda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_votes_for', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.drop_column('last_votes_for')

    # ### end Alembic commands ###
