"""changed successful to winner in round table

Revision ID: b2de8636beda
Revises: 8d7658cfdb80
Create Date: 2023-11-03 11:34:21.106414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2de8636beda'
down_revision = '8d7658cfdb80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('winner', sa.String(), nullable=True))
        batch_op.drop_column('successful_quest')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rounds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('successful_quest', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('winner')

    # ### end Alembic commands ###
